### ISSUE TITLE
Um arquivo README.md melhor seria interessante.

### ISSUE THREAD

**Issue by JonasUliana** [Pedro-Souza/value-coins#1]
Acredito que uma apresentação amigável do conteúdo do repositório, assim como o objetivo da futura (**brilhante**) aplicação, além do mais, boa iniciativa!

**Comment by Pedro-Souza** [comment]
Vamos providenciar um readme amigavel em breve

**Comment by Pedro-Souza** [comment]
Nosso amigo mandou PR para o readme <3 [https://github.com/Pedro-Souza/value-coins/pull/2](https://github.com/Pedro-Souza/value-coins/pull/2)
